package gsi

// Code generated by 'go run blockdataid_generate.go'; DO NOT EDIT.

// The hash of no input, indicating that no transactions were included.
const zeroHash = "0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8"

// The suffix of the app data ID including nTxs=0 and the corresponding hash.
const zeroHashSuffix = ":0:" + zeroHash
