//go:build !debug

// Code generated by github.com/rollchains/gordian/gassert/cmd/generate-nodebug roundlifecycle_debug.go; DO NOT EDIT.

package tsi

func (rlc *RoundLifecycle) invariantCycleFinalization() {}
