// Code generated by "stringer -type Step -trimprefix=Step ."; DO NOT EDIT.

package tsi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StepInvalid-0]
	_ = x[StepAwaitingProposal-1]
	_ = x[StepAwaitingPrevotes-2]
	_ = x[StepPrevoteDelay-3]
	_ = x[StepAwaitingPrecommits-4]
	_ = x[StepPrecommitDelay-5]
	_ = x[StepCommitWait-6]
	_ = x[StepAwaitingFinalization-7]
}

const _Step_name = "InvalidAwaitingProposalAwaitingPrevotesPrevoteDelayAwaitingPrecommitsPrecommitDelayCommitWaitAwaitingFinalization"

var _Step_index = [...]uint8{0, 7, 23, 39, 51, 69, 83, 93, 113}

func (i Step) String() string {
	if i >= Step(len(_Step_index)-1) {
		return "Step(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Step_name[_Step_index[i]:_Step_index[i+1]]
}
