//go:build !debug

// Code generated by github.com/gordian-engine/gordian/gassert/cmd/generate-nodebug kernel_debug.go; DO NOT EDIT.

package tmi

import (
	"github.com/gordian-engine/gordian/gassert"
)

func invariantReplayedHeaderResponse(env gassert.Env, err error) {}
