// Code generated by "stringer -type PBCheckStatus -trimprefix=PBCheck"; DO NOT EDIT.

package tmi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PBCheckInvalid-0]
	_ = x[PBCheckAcceptable-1]
	_ = x[PBCheckNextHeight-2]
	_ = x[PBCheckAlreadyHaveSignature-3]
	_ = x[PBCheckSignerUnrecognized-4]
	_ = x[PBCheckRoundTooOld-5]
	_ = x[PBCheckRoundTooFarInFuture-6]
}

const _PBCheckStatus_name = "InvalidAcceptableNextHeightAlreadyHaveSignatureSignerUnrecognizedRoundTooOldRoundTooFarInFuture"

var _PBCheckStatus_index = [...]uint8{0, 7, 17, 27, 47, 65, 76, 95}

func (i PBCheckStatus) String() string {
	if i >= PBCheckStatus(len(_PBCheckStatus_index)-1) {
		return "PBCheckStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PBCheckStatus_name[_PBCheckStatus_index[i]:_PBCheckStatus_index[i+1]]
}
