// Code generated by "stringer -type PHCheckStatus -trimprefix=PHCheck"; DO NOT EDIT.

package tmi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PHCheckInvalid-0]
	_ = x[PHCheckAcceptable-1]
	_ = x[PHCheckNextHeight-2]
	_ = x[PHCheckAlreadyHaveSignature-3]
	_ = x[PHCheckSignerUnrecognized-4]
	_ = x[PHCheckRoundTooOld-5]
	_ = x[PHCheckRoundTooFarInFuture-6]
}

const _PHCheckStatus_name = "InvalidAcceptableNextHeightAlreadyHaveSignatureSignerUnrecognizedRoundTooOldRoundTooFarInFuture"

var _PHCheckStatus_index = [...]uint8{0, 7, 17, 27, 47, 65, 76, 95}

func (i PHCheckStatus) String() string {
	if i >= PHCheckStatus(len(_PHCheckStatus_index)-1) {
		return "PHCheckStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PHCheckStatus_name[_PHCheckStatus_index[i]:_PHCheckStatus_index[i+1]]
}
