// Code generated by "stringer -type ViewLookupStatus -trimprefix=View"; DO NOT EDIT.

package tmi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ViewFound-0]
	_ = x[ViewBeforeCommitting-1]
	_ = x[ViewWrongCommit-2]
	_ = x[ViewOrphaned-3]
	_ = x[ViewLaterVotingRound-4]
	_ = x[ViewFuture-5]
}

const _ViewLookupStatus_name = "FoundBeforeCommittingWrongCommitOrphanedLaterVotingRoundFuture"

var _ViewLookupStatus_index = [...]uint8{0, 5, 21, 32, 40, 56, 62}

func (i ViewLookupStatus) String() string {
	if i >= ViewLookupStatus(len(_ViewLookupStatus_index)-1) {
		return "ViewLookupStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ViewLookupStatus_name[_ViewLookupStatus_index[i]:_ViewLookupStatus_index[i+1]]
}
