// Code generated by "stringer -type ViewID -trimprefix=ViewID ."; DO NOT EDIT.

package tmi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ViewIDNotFound-0]
	_ = x[ViewIDVoting-1]
	_ = x[ViewIDCommitting-2]
	_ = x[ViewIDNextRound-3]
	_ = x[ViewIDNextHeight-4]
}

const _ViewID_name = "NotFoundVotingCommittingNextRoundNextHeight"

var _ViewID_index = [...]uint8{0, 8, 14, 24, 33, 43}

func (i ViewID) String() string {
	if i >= ViewID(len(_ViewID_index)-1) {
		return "ViewID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ViewID_name[_ViewID_index[i]:_ViewID_index[i+1]]
}
