// Code generated by "stringer -type Feedback -trimprefix=Feedback"; DO NOT EDIT.

package gexchange

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FeedbackUnspecified-0]
	_ = x[FeedbackAccepted-1]
	_ = x[FeedbackRejected-2]
	_ = x[FeedbackIgnored-3]
	_ = x[FeedbackRejectAndDisconnect-4]
}

const _Feedback_name = "UnspecifiedAcceptedRejectedIgnoredRejectAndDisconnect"

var _Feedback_index = [...]uint8{0, 11, 19, 27, 34, 53}

func (i Feedback) String() string {
	if i >= Feedback(len(_Feedback_index)-1) {
		return "Feedback(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Feedback_name[_Feedback_index[i]:_Feedback_index[i+1]]
}
