//go:generate go run main.go
package gcryptotest

import (
	"crypto/ed25519"
	"fmt"
	"io"
	"text/template"
)

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
package gcryptotest

import (
	"crypto/ed25519"
)

var generatedEd25519 = []ed25519.PrivateKey{
{{- range .Keys }}
	ed25519.PrivateKey({{.}}),
{{- end }}
}
`))

func GenerateKeys(w io.Writer) error {
	keys := make([]string, 16)
	for i := range keys {
		seed := fmt.Sprintf("%032d", i) // Seed must be 32 bytes long.
		pk := ed25519.NewKeyFromSeed([]byte(seed))
		keys[i] = fmt.Sprintf("%q", pk)
	}

	return packageTemplate.Execute(w, struct {
		Keys []string
	}{
		Keys: keys,
	})
}
