//go:build !debug

// Code generated by github.com/gordian-engine/gordian/gassert/cmd/generate-nodebug component_debug.go; DO NOT EDIT.

package gserver

import (
	"github.com/gordian-engine/gordian/tm/tmengine"
	"github.com/spf13/pflag"
)

func addAssertRuleFlag(fs *pflag.FlagSet) {}

func getAssertEngineOpt(cfg map[string]any) (_ tmengine.Opt, _ error) {
	return
}
