//go:build !debug

// Code generated by github.com/rollchains/gordian/gassert/cmd/generate-nodebug component_debug.go; DO NOT EDIT.

package gserver

import (
	"github.com/rollchains/gordian/tm/tmengine"
	"github.com/spf13/pflag"
	"github.com/spf13/viper"
)

func addAssertRuleFlag(fs *pflag.FlagSet) {}

func getAssertEngineOpt(v *viper.Viper) (_ tmengine.Opt, _ error) {
	return
}
