// Code generated by "stringer -type HandleProposedBlockResult -trimprefix=HandleProposedBlock ."; DO NOT EDIT.

package tmconsensus

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HandleProposedBlockAccepted-1]
	_ = x[HandleProposedBlockAlreadyStored-2]
	_ = x[HandleProposedBlockSignerUnrecognized-3]
	_ = x[HandleProposedBlockBadBlockHash-4]
	_ = x[HandleProposedBlockBadSignature-5]
	_ = x[HandleProposedBlockRoundTooOld-6]
	_ = x[HandleProposedBlockRoundTooFarInFuture-7]
	_ = x[HandleProposedBlockInternalError-8]
}

const _HandleProposedBlockResult_name = "AcceptedAlreadyStoredSignerUnrecognizedBadBlockHashBadSignatureRoundTooOldRoundTooFarInFutureInternalError"

var _HandleProposedBlockResult_index = [...]uint8{0, 8, 21, 39, 51, 63, 74, 93, 106}

func (i HandleProposedBlockResult) String() string {
	i -= 1
	if i >= HandleProposedBlockResult(len(_HandleProposedBlockResult_index)-1) {
		return "HandleProposedBlockResult(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _HandleProposedBlockResult_name[_HandleProposedBlockResult_index[i]:_HandleProposedBlockResult_index[i+1]]
}
