// Code generated by "stringer -type LagStatus -trimprefix=LagStatus ."; DO NOT EDIT.

package tmelink

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LagStatusInitializing-0]
	_ = x[LagStatusUpToDate-1]
	_ = x[LagStatusAssumedBehind-2]
	_ = x[LagStatusKnownMissing-3]
}

const _LagStatus_name = "InitializingUpToDateAssumedBehindKnownMissing"

var _LagStatus_index = [...]uint8{0, 12, 20, 33, 45}

func (i LagStatus) String() string {
	if i >= LagStatus(len(_LagStatus_index)-1) {
		return "LagStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LagStatus_name[_LagStatus_index[i]:_LagStatus_index[i+1]]
}
